### ISSUE TITLE
Shapes are not loading

### ISSUE THREAD

**Issue by ChristopherGra** [ThomasFarmer/PotreeCraft#2]
I tried to insert countour lines to my pointcloud. The contour lines are .shp-files. I followed your tutorial on Youtube with the test data package but i keep getting the error messages:

shapefile-w3d.js:31 Fetch API cannot load file:///D:/Skyability/PotreeCraft_Project/test_data_package/test_data/output/vector_data/edges_of_the_road.dbf. URL scheme "file" is not supported.
fetchPath @ shapefile-w3d.js:31
shapefile-w3d.js:31 Fetch API cannot load file:///D:/Skyability/PotreeCraft_Project/test_data_package/test_data/output/vector_data/edges_of_the_road.shp. URL scheme "file" is not supported.
fetchPath @ shapefile-w3d.js:31
shapefile-w3d.js:31 Fetch API cannot load file:///D:/Skyability/PotreeCraft_Project/test_data_package/test_data/output/vector_data/midroad_points.dbf. URL scheme "file" is not supported.
fetchPath @ shapefile-w3d.js:31
shapefile-w3d.js:31 Fetch API cannot load file:///D:/Skyability/PotreeCraft_Project/test_data_package/test_data/output/vector_data/midroad_points.shp. URL scheme "file" is not supported.

Unfortunately, i don't have much experience with JavaScript and HTML and I can't figure out what the problem exactly is. I code only in python.
What can I do to fix this?
I hope that this information is sufficient!

**Comment by ThomasFarmer** [comment]
Hey Chris,
Maybe, we'll see - from this info i think the issue is you are not running potree in a webserver. See your file url-s start with the "file://" protocol, so i assume you just opened the local file from total commander or windows explorer and dropped it in your browser, is that correct?
I think the fix would be quite easy in your case, just navigate to your project directory, open a command line, and start the basic python webserver in that folder. it's something like "python3 -m http.server". I'm under linux now, but it should be identical under windows. After this, go to your browser and type "127.0.0.1:8000/main.html" or something as your url. This should fix it.
![Screenshot from 2020-08-25 14-31-04fvvsd](https://user-images.githubusercontent.com/23472718/91174541-b65f0f00-e6df-11ea-88fe-8ec85a1850b0.png)

**Comment by ChristopherGra** [comment]
Thank you very much, it worked!

**Comment by ThomasFarmer** [comment]
you're welcome. :) If there's another issue, feel free to open another thread.
